# =========================================
# ERD_UTILS Module (Modern & Colorful Style C)
# =========================================

from utils.db_utils import (
    list_tables,
    get_columns,
    get_foreign_keys,
    get_unique_columns
)

import streamlit.components.v1 as components


# ============================================================
# 1. Generate ultra-technical ERD (Mermaid.js)
# ============================================================

def generate_erd(conn) -> str:
    """
    Generates a technical ERD diagram in Mermaid.js format based on the structure
    of a SQLite database.

    Args:
        conn (sqlite3.Connection): Active database connection.

    Returns:
        str: Mermaid code ready to be rendered in Streamlit.

    Example:
        mermaid_code = generate_erd(conn)
        print(mermaid_code)
        # Output: "erDiagram ..."
    """

    tables = list_tables(conn)

    # Modern & colorful Mermaid style
    mermaid_code = """
    %%{init: {
      'theme': 'forest',
      'themeVariables': {
        'primaryColor': '#ffffff',
        'primaryTextColor': '#0f172a',
        'primaryBorderColor': '#1e293b',
        'lineColor': '#334155',
        'fontSize': '32px',
        'fontFamily': 'Inter, Arial, sans-serif',
        'edgeLabelBackground': '#e2e8f0',
        'entityBorderColor': '#1e293b',
        'entityBackground': '#f8fafc'
      },
      'er': {
        'layoutDirection': 'TB',
        'rankSep': 95,
        'nodeSep': 75,
        'useMaxWidth': true
      }
    }}%%
    erDiagram
    """

    relationships = []

    for table in tables:
        columns = get_columns(conn, table)
        fks = get_foreign_keys(conn, table)
        unique_cols = get_unique_columns(conn, table)

        table_id = table.replace(" ", "_")
        mermaid_code += f'    {table_id} {{\n'

        for _, col in columns.iterrows():
            name = col["name"]
            col_type = col["type"]

            tags = []
            if col["pk"]:
                tags.append("PK")
            if name in unique_cols:
                tags.append("UK")

            fk_match = fks[fks["from"] == name] if not fks.empty else None
            if fk_match is not None and not fk_match.empty:
                tags.append("FK")
                dest_table = fk_match.iloc[0]["table"].replace(" ", "_")
                relationships.append(
                    f'    {table_id} ||--o{{ {dest_table} : "{name}"'
                )

            null_info = "NOT_NULL" if col["notnull"] else "NULL"
            default_val = f"DEF:{col['dflt_value']}" if col["dflt_value"] else ""
            extra_info = f"{null_info} {default_val}".strip()

            mermaid_code += (
                f'        {col_type} {name} {",".join(tags)} "{extra_info}"\n'
            )

        mermaid_code += "    }\n"

    mermaid_code += "\n".join(set(relationships))
    return mermaid_code


# ============================================================
# 2. Render & download ERD in Streamlit
# ============================================================

def erd_to_image(mermaid_code):
    """
    Renders a Mermaid.js ERD diagram in Streamlit and allows downloading it as SVG.

    Args:
        mermaid_code (str): Mermaid code generated by generate_erd().

    Returns:
        None
    """

    html_code = f"""
    <style>
        #canvas-area {{
            background: #ffffff;
            border: 2px solid #e2e8f0;
            border-radius: 12px;
            padding: 30px;
            overflow: auto;
            max-height: 750px;
        }}

        #mermaid-renderer svg {{
            width: auto !important;
            height: auto !important;
            max-width: 100%;
            transform: scale(1.20);
            transform-origin: top left;
        }}

        .mermaid .icon {{
            display: none !important;
        }}
    </style>

    <div id="canvas-area">
        <div id="mermaid-renderer" class="mermaid">
            {mermaid_code}
        </div>
    </div>

    <div style="
        margin-top: 25px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-family: Inter, sans-serif;
    ">
        <button id="download-btn" style="
            background-color: #2563eb;
            color: white;
            padding: 12px 24px;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-weight: bold;
            font-size: 14px;
        ">
            💾 Download SVG (High Resolution)
        </button>

        <div style="
            font-size: 14px;
            color: #475569;
            background: #f8fafc;
            padding: 10px 14px;
            border-radius: 6px;
            border: 1px solid #e2e8f0;
        ">
            <b style="color:#dc2626;">PK</b>: Primary |
            <b style="color:#2563eb;">FK</b>: Foreign |
            <b style="color:#16a34a;">UK</b>: Unique |
            <b>DEF</b>: Default
        </div>
    </div>

    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';

        mermaid.initialize({{
            startOnLoad: true,
            er: {{ useMaxWidth: true, minEntityWidth: 200 }}
        }});

        document.getElementById('download-btn').addEventListener('click', function() {{
            const svgElement = document.querySelector('#mermaid-renderer svg');
            if (svgElement) {{
                const bbox = svgElement.getBBox();
                const svgClone = svgElement.cloneNode(true);
                svgClone.setAttribute("viewBox", `${{bbox.x}} ${{bbox.y}} ${{bbox.width}} ${{bbox.height}}`);
                svgClone.setAttribute("width", bbox.width);
                svgClone.setAttribute("height", bbox.height);
                svgClone.style.backgroundColor = "white";

                const serializer = new XMLSerializer();
                let source = serializer.serializeToString(svgClone);
                const url = "data:image/svg+xml;charset=utf-8," + encodeURIComponent(source);
                const link = document.createElement("a");
                link.href = url;
                link.download = "DB_Diagram_Technical.svg";
                link.click();
            }}
        }});
    </script>
    """

    components.html(html_code, height=950, scrolling=False)
