# =========================================
# NLP_UTILS Module (adapted from your Spanish version)
# =========================================
import pandas as pd
import re
from utils.db_utils import (
    list_tables,
    get_columns,
    get_foreign_keys
)
from utils.llama_utils import use_llama, modes


# ============================================================
# 1. REAL SCHEMA FOR THE LLM
# ============================================================

def get_schema_for_llm(conn):
    """
    Returns a complete and structured schema of the database.
    This schema is used as context for the LLM.
    """
    tables = list_tables(conn)
    schema = []

    for table in tables:
        columns = get_columns(conn, table)
        fks = get_foreign_keys(conn, table)

        schema.append(f"Table: {table}")

        for _, col in columns.iterrows():
            line = f"- {col['name']} | {col['type']} | PK:{col['pk']} | NULL:{col['notnull']}"
            schema.append(line)

        if not fks.empty:
            schema.append("  FOREIGN KEYS:")
            for _, fk in fks.iterrows():
                schema.append(f"    - {fk['from']} -> {fk['table']}.{fk['to']}")

        schema.append("")

    return "\n".join(schema)


# ============================================================
# 1.1 Clean SQL
# ============================================================

def clean_sql(text: str) -> str:
    """
    Cleans SQL generated by the LLM:
    - Removes ```sql and ``` blocks
    - Removes -- and /* */ comments
    - Extracts the full query even if it is multi-line
    - Returns only valid SQL
    """

    # Remove code blocks
    text = text.replace("```sql", "")
    text = text.replace("```", "")
    text = text.strip()

    # Remove single-line comments --
    text = re.sub(r"--.*", "", text)

    # Remove multi-line comments /* ... */
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)

    # Find the first valid SQL keyword
    sql_start = None
    keywords = [
        "SELECT", "INSERT", "UPDATE", "DELETE",
        "CREATE", "DROP", "ALTER", "WITH"
    ]

    lines = text.split("\n")
    for i, line in enumerate(lines):
        if any(line.strip().upper().startswith(k) for k in keywords):
            sql_start = i
            break

    if sql_start is None:
        return ""

    # Rebuild SQL from the line where it starts
    sql = "\n".join(lines[sql_start:]).strip()

    # Remove trailing dot if the model adds it
    if sql.endswith("."):
        sql = sql[:-1]

    return sql.strip()


# ============================================================
# 2. GENERATE SQL FROM NATURAL LANGUAGE
# ============================================================

def nlp_to_sql(text: str, schema: str) -> str:
    """
    Generates real SQL using the real database schema.
    It does NOT invent tables or columns.
    """

    prompt = f"""
Convert the following request into a valid SQL query for SQLite.

STRICT RULES:
- Use ONLY the tables and columns from the schema.
- Do NOT invent tables.
- Do NOT invent columns.
- Do NOT invent relationships.
- If the user asks for something impossible, return:
  SELECT 'There is no information related to this request in the database' AS message;
- Return ONLY SQL, no explanations.
- Do NOT use ```sql or ``` blocks in the response.
- Use explicit JOINs when necessary.
- Use LIMIT instead of SELECT TOP.

REAL SCHEMA:
{schema}

USER REQUEST:
{text}

SQL:
"""

    sql_generated = use_llama(prompt, role_system=modes["generate_sql"])
    return clean_sql(sql_generated.strip())


# ============================================================
# 3. EXPLAIN SQL USING REAL DATA
# ============================================================

def explain_sql(sql: str, columns: list, rows: list, schema: str) -> str:
    """
    Explains a SQL query using:
    - the real SQL
    - the real columns
    - the real data
    - the real schema
    """

    df_preview = pd.DataFrame(rows, columns=columns).head(10).to_markdown()

    prompt = f"""
You are an expert SQL teacher.

Explain the following query using ONLY the information from the real schema and the real data.

SQL:
{sql}

COLUMNS:
{columns}

DATA (first 10 rows):
{df_preview}

REAL SCHEMA:
{schema}

RESPONSE FORMAT:
1. Query objective
2. Tables involved
3. Columns used
4. Relationships used
5. Step-by-step explanation
6. Final result
"""

    explanation = use_llama(prompt, role_system=modes["explain"])
    return explanation.strip()


# ============================================================
# 4. VALIDATE GENERATED SQL
# ============================================================

def validate_generated_sql(sql: str, conn):
    """
    Checks whether the SQL generated by the LLM is valid.
    """
    try:
        cursor = conn.cursor()
        cursor.execute(sql)
        return True, None
    except Exception as e:
        return False, str(e)


# ============================================================
# 5. AUTO-FIX GENERATED SQL
# ============================================================

def fix_generated_sql(sql: str, error: str, schema: str) -> str:
    """
    If the generated SQL fails, the LLM fixes it using:
    - the original SQL
    - the real SQLite error
    - the real schema
    """

    prompt = f"""
Fix the following SQL query based on the real SQLite error.

ORIGINAL SQL:
{sql}

SQLITE ERROR:
{error}

REAL SCHEMA:
{schema}

RULES:
- Do NOT invent tables.
- Do NOT invent columns.
- Do NOT invent relationships.
- Use ONLY what appears in the schema.
- Return ONLY the corrected SQL, no explanations.
- Do NOT use ```sql or ``` blocks.

CORRECTED SQL:
"""

    fixed_sql = use_llama(prompt, role_system=modes["generate_sql"])
    return clean_sql(fixed_sql.strip())
